### PR TITLE
Change author

### LINKED ISSUE #14: Author is `Simone Silvestri`
Usually we try to encourage contributions by stating a broader author list

https://github.com/CliMA/OrthogonalSphericalShellGrids.jl/blob/486636fe7ba96145c1c88fcbecdf9b07d0542865/Project.toml#L3

For example `Oceananigans` uses `"Climate Modeling Alliance and contributors"`:

https://github.com/CliMA/Oceananigans.jl/blob/406eb9c5c7a9fc86947747116128c8c1ba4c93d4/Project.toml#L3

### PR DESCRIPTION
**Pull request by simone-silvestri**
closes #14

### CODE REVIEW

**Comment by simone-silvestri** [comment]
There seems to be some problem with the `BoundaryCondition`. Did we introduce breaking changes in Oceananigans? I thought the changes were not breaking.

**Review by glwagner — APPROVED** [review]

**Comment by navidcy** [comment]
Hm... We call a change breaking if it's breaking for the user-facing API we export...

**Comment by navidcy** [comment]
> Hm... We call a change breaking if it's breaking for the user-facing API we export...

I take it back! Things shouldn't break in a patch release!

**Comment by navidcy** [comment]
Do we need to change the license?

**Pull request merged**
